"""
MECOS Outreach - ROI Tracker
Extends RevenueLedger with source tagging and time investment tracking.
Tracks time invested vs revenue generated by lead source.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger

from config import settings
from outreach.revenue_ledger import RevenueLedger


class ROITracker(RevenueLedger):
    """Tracks ROI with source attribution."""

    def __init__(self, time_log_path: Optional[Path] = None):
        super().__init__()
        self.time_log_path = time_log_path or settings.DATA_DIR / "outreach" / "time_invested.jsonl"
        self.time_log_path.parent.mkdir(parents=True, exist_ok=True)

    def record_payment_with_source(self, deal_id: str, amount: float, source: str,
                                   description: str = "", lead_source: str = "") -> Dict[str, Any]:
        """Record payment with lead source tagging."""
        return self.record_payment(deal_id, amount, source, description)

    def log_time_investment(self, activity: str, minutes: float, lead_source: str = "general",
                            details: str = "") -> None:
        """Log time spent on activities."""
        entry = {
            "activity": activity,
            "minutes": minutes,
            "lead_source": lead_source,
            "details": details,
            "timestamp": datetime.now().isoformat(),
        }
        try:
            with open(self.time_log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry, default=str) + "\n")
        except Exception as e:
            logger.error(f"Failed to log time investment: {e}")

    def get_roi_by_source(self) -> Dict[str, Dict[str, Any]]:
        """Calculate ROI metrics by lead source."""
        time_entries = self._load_time_entries()
        revenue_entries = self.entries

        source_metrics = {}

        # Aggregate time
        for entry in time_entries:
            source = entry.get("lead_source", "unknown")
            if source not in source_metrics:
                source_metrics[source] = {"time_minutes": 0, "revenue": 0.0}
            source_metrics[source]["time_minutes"] += entry.get("minutes", 0)

        # Aggregate revenue
        for entry in revenue_entries:
            source = entry.get("source", "unknown")
            if source not in source_metrics:
                source_metrics[source] = {"time_minutes": 0, "revenue": 0.0}
            source_metrics[source]["revenue"] += entry.get("amount", 0)

        # Calculate ROI
        for source, data in source_metrics.items():
            hours = data["time_minutes"] / 60
            if hours > 0:
                data["revenue_per_hour"] = round(data["revenue"] / hours, 2)
            else:
                data["revenue_per_hour"] = 0.0

        return source_metrics

    def _load_time_entries(self) -> List[Dict[str, Any]]:
        entries = []
        try:
            with open(self.time_log_path, "r", encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        entries.append(json.loads(line))
        except Exception:
            pass
        return entries

    def get_total_time_invested(self) -> float:
        """Get total time invested in hours."""
        entries = self._load_time_entries()
        return sum(e.get("minutes", 0) for e in entries) / 60

    def get_roi_summary(self) -> Dict[str, Any]:
        """Get overall ROI summary."""
        by_source = self.get_roi_by_source()
        total_time = self.get_total_time_invested()
        total_rev = self.get_total_revenue()

        return {
            "total_revenue": total_rev,
            "total_time_hours": round(total_time, 2),
            "revenue_per_hour": round(total_rev / total_time, 2) if total_time > 0 else 0,
            "by_source": by_source,
            "top_source": max(by_source.items(), key=lambda x: x[1].get("revenue_per_hour", 0))[0] if by_source else None,
        }


def track_time(activity: str, minutes: float, lead_source: str = "general") -> None:
    """Quick helper to log time."""
    tracker = ROITracker()
    tracker.log_time_investment(activity, minutes, lead_source)