"""
MECOS Outreach - Weekly Markdown Report
Generates weekly performance Markdown for GitLab Pages / local review.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict

from loguru import logger

from config import settings
from outreach.analytics.funnel import FunnelAnalytics
from outreach.roi_tracker import ROITracker


class WeeklyReport:
    """Generate weekly outreach performance Markdown reports."""

    def __init__(self, report_dir: Path | None = None):
        self.report_dir = report_dir or settings.DATA_DIR / "outreach" / "reports"
        self.report_dir.mkdir(parents=True, exist_ok=True)
        self.funnel = FunnelAnalytics()
        self.roi = ROITracker()

    def generate(self) -> Path:
        now = datetime.now()
        week_start = now - timedelta(days=7)
        week_label = week_start.strftime("%Y-%m-%d") + "_to_" + now.strftime("%Y-%m-%d")

        metrics = self.funnel.get_funnel_metrics()
        funnel_counts = metrics.get("counts", {})
        funnel_rates = metrics.get("rates", {})
        roi = self.roi.get_roi_by_source()
        deal_summary = self.roi.get_summary()

        lines = [
            f"# MECOS Outreach Weekly Report",
            f"",
            f"**Week:** {week_label}  ",
            f"**Generated:** {now.isoformat()}",
            f"",
            f"---",
            f"",
            f"## Funnel Metrics (All Time)",
            f"",
            f"| Metric | Count |",
            f"| :--- | :--- |",
            f"| Leads Discovered | {funnel_counts.get('leads_discovered', 0)} |",
            f"| Emails Sent | {funnel_counts.get('emails_sent', 0)} |",
            f"| Replies Received | {funnel_counts.get('replies_received', 0)} |",
            f"| Meetings Booked | {funnel_counts.get('meetings_booked', 0)} |",
            f"| Deals Won | {funnel_counts.get('deals_won', 0)} |",
            f"| Revenue | ${funnel_counts.get('revenue', 0):.2f} |",
            f"",
            f"## Conversion Rates",
            f"",
            f"| Rate | Value |",
            f"| :--- | :--- |",
            f"| Reply Rate | {funnel_rates.get('reply_rate', 0):.1%} |",
            f"| Meeting Rate | {funnel_rates.get('meeting_rate', 0):.1%} |",
            f"| Close Rate | {funnel_rates.get('close_rate', 0):.1%} |",
            f"",
            f"## Revenue by Source",
            f"",
            f"| Source | Revenue |",
            f"| :--- | :--- |",
        ]

        for src, data in sorted(roi.items(), key=lambda x: x[1].get("revenue", 0), reverse=True):
            revenue = data.get("revenue", 0)
            if revenue > 0:
                lines.append(f"| {src} | ${revenue:.2f} |")

        if not roi:
            lines.append(f"| (none) | $0.00 |")

        lines += [
            f"",
            f"## Deals Summary",
            f"",
            f"- Total Deals: {deal_summary.get('total_deals', 0)}",
            f"- Total Revenue: ${deal_summary.get('total_revenue', 0):.2f}",
            f"- Avg Deal Size: ${deal_summary.get('avg_deal_size', 0):.2f}",
            f"",
            f"## Top Performing Lead Sources",
            f"",
            f"| Source | Deals | Revenue |",
            f"| :--- | :--- | :--- |",
        ]

        by_source = deal_summary.get("by_source", {})
        for src, data in sorted(by_source.items(), key=lambda x: x[1].get("revenue", 0), reverse=True)[:10]:
            lines.append(f"| {src} | {data.get('count', 0)} | ${data.get('revenue', 0):.2f} |")

        if not by_source:
            lines.append(f"| (none) | 0 | $0.00 |")

        lines += [
            f"",
            f"---",
            f"*Auto-generated by MECOS Outreach*",
            f"",
        ]

        report_path = self.report_dir / f"weekly_{week_label}.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Weekly report generated: {report_path}")
        return report_path
